module.exports = {
  dependencies: {
    base: [
      'babel-polyfill@6',
      'whatwg-fetch@2',
    ],
    react: [
      'react@16',
      'react-dom@16',
      'react-hot-loader@3',
      'react-router@3',
    ],
  },
  devDependencies: {
    base: [
      '@types/node@8',
      '@types/webpack-env@1',
      'awesome-typescript-loader@4',
      'babel-core@6',
      'babel-preset-env@1',
      'cross-env@5',
      'css-loader@0',
      'env-cmd@7',
      'file-loader@1',
      'html-webpack-plugin@3',
      'if-env@1',
      'node-sass@4',
      'rimraf@2',
      'sass-loader@6',
      'tslint@5',
      'tslint-loader@3',
      'tslint-react@3',
      'typescript@2',
      'url-loader@1',
      'webpack-merge@4',
    ],
    jest: [
      '@types/enzyme@3',
      '@types/jest@22',
      'enzyme@3',
      'enzyme-adapter-react-16@1',
      'enzyme-to-json@3',
      'identity-obj-proxy@3',
      'jest@22',
      'raf@3',
      'ts-jest@22',
    ],
    react: [
      '@types/react@16',
      '@types/react-dom@16',
      '@types/react-hot-loader@3',
      '@types/react-router@3',
    ],
    webpack3: [
      'extract-text-webpack-plugin@3',
      'style-loader@0',
      'webpack@3',
      'webpack-dev-server@2',
    ],
    webpack4: [
      'mini-css-extract-plugin@3',
      'webpack@4',
      'webpack-dev-server@3',
    ],
  },
}
